// V9 成就系统 - 成就数据定义
// 分类: combo(连击) | score(分数) | collect(收集) | challenge(挑战) | special(特殊)

// 成就定义
export const ACHIEVEMENTS = [
  // === 连续类 (Combo) ===
  {
    id: 'combo_5',
    name: '连击新星',
    desc: '达成5连击',
    category: 'combo',
    condition: { type: 'combo', value: 5 },
    reward: { coins: 10 },
    icon: '🔥',
    tier: 1,
  },
  {
    id: 'combo_10',
    name: '连击达人',
    desc: '达成10连击',
    category: 'combo',
    condition: { type: 'combo', value: 10 },
    reward: { coins: 25 },
    icon: '🔥',
    tier: 2,
  },
  {
    id: 'combo_20',
    name: '连击之王',
    desc: '达成20连击',
    category: 'combo',
    condition: { type: 'combo', value: 20 },
    reward: { coins: 50, title: '连击之王' },
    icon: '🔥',
    tier: 3,
  },
  {
    id: 'combo_50',
    name: '连击神话',
    desc: '达成50连击',
    category: 'combo',
    condition: { type: 'combo', value: 50 },
    reward: { coins: 100, title: '连击神话' },
    icon: '🔥',
    tier: 4,
  },

  // === 分数类 (Score) ===
  {
    id: 'score_10',
    name: '初出茅庐',
    desc: '单局得分达到10',
    category: 'score',
    condition: { type: 'score', value: 10 },
    reward: { coins: 5 },
    icon: '⭐',
    tier: 1,
  },
  {
    id: 'score_50',
    name: '小有所成',
    desc: '单局得分达到50',
    category: 'score',
    condition: { type: 'score', value: 50 },
    reward: { coins: 20 },
    icon: '⭐',
    tier: 2,
  },
  {
    id: 'score_100',
    name: '高手入门',
    desc: '单局得分达到100',
    category: 'score',
    condition: { type: 'score', value: 100 },
    reward: { coins: 50, title: '高手' },
    icon: '⭐',
    tier: 3,
  },
  {
    id: 'score_200',
    name: '顶尖高手',
    desc: '单局得分达到200',
    category: 'score',
    condition: { type: 'score', value: 200 },
    reward: { coins: 100, title: '顶尖高手' },
    icon: '⭐',
    tier: 4,
  },
  {
    id: 'score_500',
    name: '独孤求败',
    desc: '单局得分达到500',
    category: 'score',
    condition: { type: 'score', value: 500 },
    reward: { coins: 200, title: '独孤求败', skin: 'cyber' },
    icon: '⭐',
    tier: 5,
  },
  {
    id: 'score_1000',
    name: '传说级别',
    desc: '单局得分达到1000',
    category: 'score',
    condition: { type: 'score', value: 1000 },
    reward: { coins: 500, title: '传说' },
    icon: '⭐',
    tier: 5,
  },

  // === 挑战类 (Challenge) ===
  {
    id: 'first_game',
    name: '初次游戏',
    desc: '完成第一局游戏',
    category: 'challenge',
    condition: { type: 'games_played', value: 1 },
    reward: { coins: 10 },
    icon: '🏆',
    tier: 1,
  },
  {
    id: 'games_10',
    name: '老手',
    desc: '累计完成10局游戏',
    category: 'challenge',
    condition: { type: 'games_played', value: 10 },
    reward: { coins: 30 },
    icon: '🏆',
    tier: 2,
  },
  {
    id: 'games_50',
    name: '资深玩家',
    desc: '累计完成50局游戏',
    category: 'challenge',
    condition: { type: 'games_played', value: 50 },
    reward: { coins: 80 },
    icon: '🏆',
    tier: 3,
  },
  {
    id: 'games_100',
    name: '骨灰级玩家',
    desc: '累计完成100局游戏',
    category: 'challenge',
    condition: { type: 'games_played', value: 100 },
    reward: { coins: 150, title: '骨灰级' },
    icon: '🏆',
    tier: 4,
  },
  {
    id: 'timed_first',
    name: '限时挑战者',
    desc: '完成第一次限时挑战',
    category: 'challenge',
    condition: { type: 'timed_games', value: 1 },
    reward: { coins: 15 },
    icon: '⏱️',
    tier: 1,
  },
  {
    id: 'timed_10',
    name: '时间管理者',
    desc: '累计完成10次限时挑战',
    category: 'challenge',
    condition: { type: 'timed_games', value: 10 },
    reward: { coins: 50 },
    icon: '⏱️',
    tier: 2,
  },
  {
    id: 'timed_score_30',
    name: '限时新星',
    desc: '限时模式得分达到30',
    category: 'challenge',
    condition: { type: 'timed_score', value: 30 },
    reward: { coins: 20 },
    icon: '⏱️',
    tier: 1,
  },
  {
    id: 'timed_score_50',
    name: '限时达人',
    desc: '限时模式得分达到50',
    category: 'challenge',
    condition: { type: 'timed_score', value: 50 },
    reward: { coins: 50 },
    icon: '⏱️',
    tier: 2,
  },
  {
    id: 'timed_score_100',
    name: '限时之王',
    desc: '限时模式得分达到100',
    category: 'challenge',
    condition: { type: 'timed_score', value: 100 },
    reward: { coins: 100, title: '限时之王' },
    icon: '⏱️',
    tier: 3,
  },
  {
    id: 'level_clear_1',
    name: '关卡先锋',
    desc: '通关任意关卡',
    category: 'challenge',
    condition: { type: 'levels_cleared', value: 1 },
    reward: { coins: 20 },
    icon: '🌟',
    tier: 1,
  },
  {
    id: 'level_clear_5',
    name: '关卡征服者',
    desc: '累计通关5个关卡',
    category: 'challenge',
    condition: { type: 'levels_cleared', value: 5 },
    reward: { coins: 60 },
    icon: '🌟',
    tier: 2,
  },

  // === 收集类 (Collect) ===
  {
    id: 'coins_collect_100',
    name: '小有积蓄',
    desc: '累计获得100金币',
    category: 'collect',
    condition: { type: 'total_coins_earned', value: 100 },
    reward: { coins: 0 },
    icon: '🪙',
    tier: 1,
  },
  {
    id: 'coins_collect_500',
    name: '金币收藏家',
    desc: '累计获得500金币',
    category: 'collect',
    condition: { type: 'total_coins_earned', value: 500 },
    reward: { coins: 0 },
    icon: '🪙',
    tier: 2,
  },
  {
    id: 'coins_collect_1000',
    name: '金币大亨',
    desc: '累计获得1000金币',
    category: 'collect',
    condition: { type: 'total_coins_earned', value: 1000 },
    reward: { coins: 0 },
    icon: '🪙',
    tier: 3,
  },
  {
    id: 'skins_collect_2',
    name: '皮肤爱好者',
    desc: '拥有2个皮肤',
    category: 'collect',
    condition: { type: 'owned_skins', value: 2 },
    reward: { coins: 30 },
    icon: '👔',
    tier: 1,
  },
  {
    id: 'skins_collect_all',
    name: '时尚达人',
    desc: '拥有全部皮肤',
    category: 'collect',
    condition: { type: 'owned_skins', value: 4 },
    reward: { coins: 100 },
    icon: '👔',
    tier: 2,
  },

  // === 特殊类 (Special) ===
  {
    id: 'no_hit_game',
    name: '完美主义者',
    desc: '一命不死完成游戏(无尽模式)',
    category: 'special',
    condition: { type: 'no_hit_game', value: true },
    reward: { coins: 100, title: '完美主义者' },
    icon: '💎',
    tier: 3,
  },
  {
    id: 'high_combo_no_death',
    name: '冷血刺客',
    desc: '20连击且一命不死结束游戏',
    category: 'special',
    condition: { type: 'high_combo_no_death', value: 20 },
    reward: { coins: 150, title: '冷血刺客' },
    icon: '🗡️',
    tier: 4,
  },
  {
    id: 'lucky_7',
    name: '幸运7',
    desc: '在限时模式中得到7以上连击',
    category: 'special',
    condition: { type: 'lucky_combo', value: 7 },
    reward: { coins: 50 },
    icon: '🍀',
    tier: 2,
  },
  {
    id: 'comeback',
    name: '绝地反击',
    desc: '只剩1命时获得20分以上',
    category: 'special',
    condition: { type: 'comeback', value: 20 },
    reward: { coins: 80 },
    icon: '🌅',
    tier: 3,
  },
  {
    id: 'speed_demon',
    name: '速度恶魔',
    desc: '在最高速档位获得50分',
    category: 'special',
    condition: { type: 'speed_score', value: 50, speed: 180 },
    reward: { coins: 100 },
    icon: '⚡',
    tier: 4,
  },
]

// 成就分类
export const ACHIEVEMENT_CATEGORIES = [
  { id: 'all', name: '全部', icon: '📋' },
  { id: 'combo', name: '连击', icon: '🔥' },
  { id: 'score', name: '分数', icon: '⭐' },
  { id: 'challenge', name: '挑战', icon: '🏆' },
  { id: 'collect', name: '收集', icon: '🪙' },
  { id: 'special', name: '特殊', icon: '💎' },
]

// 称号列表
export const TITLES = [
  { id: '连击之王', name: '连击之王', icon: '🔥' },
  { id: '连击神话', name: '连击神话', icon: '🔥' },
  { id: '高手', name: '高手', icon: '⭐' },
  { id: '顶尖高手', name: '顶尖高手', icon: '⭐' },
  { id: '独孤求败', name: '独孤求败', icon: '⭐' },
  { id: '传说', name: '传说', icon: '⭐' },
  { id: '骨灰级', name: '骨灰级', icon: '🏆' },
  { id: '限时之王', name: '限时之王', icon: '⏱️' },
  { id: '完美主义者', name: '完美主义者', icon: '💎' },
  { id: '冷血刺客', name: '冷血刺客', icon: '🗡️' },
]

// 存储键名
export const STORAGE_ACHIEVEMENTS = 'dsw_v9_achievements'
export const STORAGE_STATS = 'dsw_v9_stats'
export const STORAGE_TITLES = 'dsw_v9_titles'
export const STORAGE_TOTAL_COINS_EARNED = 'dsw_v9_total_coins_earned'

// 初始成就状态
export const initialAchievementState = () => {
  const unlocked = {}
  ACHIEVEMENTS.forEach(a => { unlocked[a.id] = false })
  return unlocked
}

// 初始统计数据
export const initialStats = () => ({
  gamesPlayed: 0,
  timedGames: 0,
  levelsCleared: 0,
  totalCoinsEarned: 0,
  maxCombo: 0,
  maxScore: 0,
  maxTimedScore: 0,
  ownedSkins: ['default'], // 默认拥有经典皮肤
  // 用于特殊成就检测的临时数据(每局重置)
  lastGameNoDeath: false,
  lastGameMaxCombo: 0,
  lastGameScore: 0,
  lastGameLivesAtEnd: 3,
  lastGameMaxSpeed: 800,
  // 用于 comeback 成就
  hadOneLife: false,
  scoredAfterOneLife: 0,
})
